---
title: "K-Means Clustering Pokemon"
author: "Lucas Mendicino"
date: "11/9/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(dplyr)
```


```{r }
pokemon <- read.csv("~/Desktop/pokemon.csv", header=TRUE)

pokemon <- pokemon %>% select(hp, attack, defense, sp_attack, sp_defense, speed)
```

```{r}
summary(pokemon)

```

k-means
```{r}
# Initialize total within sum of squares error: wss
wss <- 0

# Look over 1 to 15 possible clusters
for (i in 1:15) {
  # Fit the model: km.out
  km.out <- kmeans(pokemon, centers = i, nstart = 20, iter.max = 50)
  # Save the within cluster sum of squares
  wss[i] <- km.out$tot.withinss
}

# Produce a scree plot
plot(1:15, wss, type = "b", 
     xlab = "Number of Clusters", 
     ylab = "Within groups sum of squares")

# Select number of clusters (2, 3, 4 probably OK)
k <- 3

# Build model with k clusters: km.out
km.out <- kmeans(pokemon, centers = k, nstart = 20, iter.max = 50)

# View the resulting model
km.out

# Plot of Defense vs. Speed by cluster membership
plot(pokemon[, c("defense", "speed")],
     col = km.out$cluster,
     main = paste("k-means clustering of Pokemon with", k, "clusters"),
     xlab = "defense", ylab = "speed")

```

hierarchical clustering

```{r}
# View column means
colMeans(pokemon)

# View column standard deviations
apply(pokemon, 2, sd)

# Scale the data
pokemon.scaled <- scale(pokemon)

# Create hierarchical clustering model: hclust.pokemon
hclust.pokemon <- hclust(d = dist(pokemon.scaled), method = "complete")

cut.pokemon <- cutree(hclust.pokemon, k = 3)
```

```{r}
table(km.pokemon$cluster, cut.pokemon)
```



