---
title: "Unsupervised Clustering Pokemon"
author: "Lucas Mendicino"
date: "11/9/2021"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(dplyr)
```


```{r}
pokemon <- read.csv("~/Desktop/pokemon.csv", header=TRUE)

pokemon <- pokemon %>% select(name, hp, attack, defense, sp_attack, sp_defense, speed)
```

```{r}
summary(pokemon)

```

k-means
```{r}
# Initialize total within sum of squares error: wss
wss <- 0

# Look over 1 to 15 possible clusters
for (i in 1:15) {
  # Fit the model: km.out
  km.out <- kmeans(pokemon[-1], centers = i, nstart = 20, iter.max = 50)
  # Save the within cluster sum of squares
  wss[i] <- km.out$tot.withinss
}

# Produce a scree plot
plot(1:15, wss, type = "b", 
     xlab = "Number of Clusters", 
     ylab = "Within groups sum of squares")

# Select number of clusters (2, 3, 4 probably OK)
k <- 3

# Build model with k clusters: km.out
km.out <- kmeans(pokemon[-1], centers = k, nstart = 20, iter.max = 50)

# View the resulting model
km.out

# Plot of Defense vs. Speed by cluster membership
plot(pokemon[-1][, c("defense", "speed")],
     col = km.out$cluster,
     main = paste("k-means clustering of Pokemon with", k, "clusters"),
     xlab = "defense", ylab = "speed")

```

```{r}

plot(pokemon[, c("hp", "attack")],
     col = km.out$cluster,
     main = paste("k-means clustering of Pokemon with", k, "clusters"),
     xlab = "hp", ylab = "attack")

```

hierarchical clustering

```{r}
# View column means
colMeans(pokemon[-1]) 

# View column standard deviations
apply(pokemon[-1], 2, sd)

# Scale the data
pokemon.scaled <- scale(pokemon[-1])

# Create hierarchical clustering model: hclust.pokemon
hclust.pokemon <- hclust(d = dist(pokemon.scaled), method = "complete")

cut.pokemon <- cutree(hclust.pokemon, k = 3)
```

```{r}
plot(hclust.pokemon)
```


```{r}
pokemon.scaled <- scale(pokemon)
hclust.pokemon <- hclust(d = dist(pokemon.scaled), method = "complete")
km.pokemon <- kmeans(pokemon.scaled, centers = 3, 
                     nstart = 20, iter.max = 50)

cut.pokemon <- cutree(hclust.pokemon, k = 3)

table(km.pokemon$cluster, cut.pokemon)
cut.pokemon
```



PCA
```{r}
pca.out <- prcomp(pokemon[-1], scale = TRUE)
summary(pca.out)
```

```{r}
biplot(pca.out)
```

```{r}
pca.var <- pca.out$sdev^2
pve <- pca.var/sum(pca.var)

plot(pve, xlab = "Principal Component",
     ylab = "Proportion of Variance Explained",
     ylim = c(0,1), type = "b")
```

```{r}
plot(pve, xlab = "Principal Component",
     ylab = "Proportion of Variance Explained",
     ylim = c(0, 1), type = "b")

# Plot cumulative proportion of variance explained
plot(cumsum(pve), xlab = "Principal Component",
     ylab = "Cumulative Proportion of Variance Explained",
     ylim = c(0, 1), type = "b")


```



```{r}
# PCA model with scaling: pr.with.scaling
pr.with.scaling <- prcomp(pokemon[-1], scale = TRUE)

# PCA model without scaling: pr.without.scaling
pr.without.scaling <- prcomp(pokemon[-1], scale = FALSE)

# Create biplots of both for comparison
biplot(pr.with.scaling)
biplot(pr.without.scaling)


```



